Document: webmenu-editor
Title: Debian webmenu-editor Manual
Author: <insert document author here>
Abstract: This manual describes what webmenu-editor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/webmenu-editor/webmenu-editor.sgml.gz

Format: postscript
Files: /usr/share/doc/webmenu-editor/webmenu-editor.ps.gz

Format: text
Files: /usr/share/doc/webmenu-editor/webmenu-editor.text.gz

Format: HTML
Index: /usr/share/doc/webmenu-editor/html/index.html
Files: /usr/share/doc/webmenu-editor/html/*.html
